"""Dynamic Path Composition — data models.

Defines the structure for LLM-generated skill execution plans.
"""
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class DynamicPathStep(BaseModel):
    """One step in a dynamically composed execution chain."""

    skill_id: str = Field(description="Target skill ID from registry")
    action: str = Field(default="execute", description="Skill action/method to call")
    input_mapping: dict[str, str] = Field(
        default_factory=dict,
        description=(
            "Maps step input field names to sources. "
            "Values starting with '$user.' → user input field. "
            "Values starting with '$step_N.' → output of step N. "
            "Values without prefix → literal value."
        ),
    )
    description: str = Field(default="", description="Why this step exists in the chain")


class DynamicPathPlan(BaseModel):
    """Complete execution plan generated by LLM."""

    goal: str = Field(description="What the user wants to achieve")
    steps: list[DynamicPathStep] = Field(
        min_length=1,
        max_length=10,
        description="Ordered sequence of skill calls",
    )
    reasoning: str = Field(default="", description="Why this plan was chosen")
